Module modStoredValue_DTStoppage
    Public DTstoValue_ShiftCode As String
    Public DTstoValue_UserName As String
    Public DTstoValue_UserID As String
    Public DTstoValue_StoppageDetails As String
    Public DTstoValue_DTType As String
    Public DTstoValue_StartTime As String
    Public DTstoValue_DTReason As String
    Public DTstoValue_CMeasure As String
    Public DTstoValue_AckDate As String
    Public DTstoValue_EndTime As String
    Public DTstoValue_RunTime As String
    Public DTstoValue_TtlDTmins As Decimal
    Public DTstoValue_TtlRrpTmins As Decimal
    Public DTstoValue_ForQAVeri As String
    Public DTstoValue_TtlVeriMins As Decimal
    Public DTstoValue_TtlFailFreq As Integer
    Public DTstoValue_DTStatus As String
    Public DTstoValue_JOCode As String
    Public DTstoValue_MachineID As String

    'Store Value @ QA Stoppage per machine (MC1SVQAStop)
    Public modMC1SVQAStop_stShiftCode As String
    Public modMC2SVQAStop_stShiftCode As String
    Public modMC3SVQAStop_stShiftCode As String
    Public modMC4SVQAStop_stShiftCode As String
    Public modMC5SVQAStop_stShiftCode As String
    Public modMC6SVQAStop_stShiftCode As String
    Public modMC7SVQAStop_stShiftCode As String
    Public modMC8SVQAStop_stShiftCode As String
    Public modMC9SVQAStop_stShiftCode As String
    Public modMC10SVQAStop_stShiftCode As String
    Public modMC11SVQAStop_stShiftCode As String
    Public modMC12SVQAStop_stShiftCode As String
    Public modMC13SVQAStop_stShiftCode As String
    Public modMC14SVQAStop_stShiftCode As String
    Public modMC15SVQAStop_stShiftCode As String
    Public modMC16SVQAStop_stShiftCode As String
    Public modMC17SVQAStop_stShiftCode As String
    Public modMC18SVQAStop_stShiftCode As String
    Public modMC19SVQAStop_stShiftCode As String

    Public modMC1SVQAStop_ As String
    Public modMC2SVQAStop_ As String
    Public modMC3SVQAStop_ As String
    Public modMC4SVQAStop_ As String
    Public modMC5SVQAStop_ As String
    Public modMC6SVQAStop_ As String
    Public modMC7SVQAStop_ As String
    Public modMC8SVQAStop_ As String
    Public modMC9SVQAStop_ As String
    Public modMC10SVQAStop_ As String
    Public modMC11SVQAStop_ As String
    Public modMC12SVQAStop_ As String
    Public modMC13SVQAStop_ As String
    Public modMC14SVQAStop_ As String
    Public modMC15SVQAStop_ As String
    Public modMC16SVQAStop_ As String
    Public modMC17SVQAStop_ As String
    Public modMC18SVQAStop_ As String
    Public modMC19SVQAStop_ As String

    Public modMC1SVQAStop_stUserName As String
    Public modMC2SVQAStop_stUserName As String
    Public modMC3SVQAStop_stUserName As String
    Public modMC4SVQAStop_stUserName As String
    Public modMC5SVQAStop_stUserName As String
    Public modMC6SVQAStop_stUserName As String
    Public modMC7SVQAStop_stUserName As String
    Public modMC8SVQAStop_stUserName As String
    Public modMC9SVQAStop_stUserName As String
    Public modMC10SVQAStop_stUserName As String
    Public modMC11SVQAStop_stUserName As String
    Public modMC12SVQAStop_stUserName As String
    Public modMC13SVQAStop_stUserName As String
    Public modMC14SVQAStop_stUserName As String
    Public modMC15SVQAStop_stUserName As String
    Public modMC16SVQAStop_stUserName As String
    Public modMC17SVQAStop_stUserName As String
    Public modMC18SVQAStop_stUserName As String
    Public modMC19SVQAStop_stUserName As String

    Public modMC1SVQAStop_stUserID As String
    Public modMC2SVQAStop_stUserID As String
    Public modMC3SVQAStop_stUserID As String
    Public modMC4SVQAStop_stUserID As String
    Public modMC5SVQAStop_stUserID As String
    Public modMC6SVQAStop_stUserID As String
    Public modMC7SVQAStop_stUserID As String
    Public modMC8SVQAStop_stUserID As String
    Public modMC9SVQAStop_stUserID As String
    Public modMC10SVQAStop_stUserID As String
    Public modMC11SVQAStop_stUserID As String
    Public modMC12SVQAStop_stUserID As String
    Public modMC13SVQAStop_stUserID As String
    Public modMC14SVQAStop_stUserID As String
    Public modMC15SVQAStop_stUserID As String
    Public modMC16SVQAStop_stUserID As String
    Public modMC17SVQAStop_stUserID As String
    Public modMC18SVQAStop_stUserID As String
    Public modMC19SVQAStop_stUserID As String

    Public modMC1SVQAStop_stDTType As String
    Public modMC2SVQAStop_stDTType As String
    Public modMC3SVQAStop_stDTType As String
    Public modMC4SVQAStop_stDTType As String
    Public modMC5SVQAStop_stDTType As String
    Public modMC6SVQAStop_stDTType As String
    Public modMC7SVQAStop_stDTType As String
    Public modMC8SVQAStop_stDTType As String
    Public modMC9SVQAStop_stDTType As String
    Public modMC10SVQAStop_stDTType As String
    Public modMC11SVQAStop_stDTType As String
    Public modMC12SVQAStop_stDTType As String
    Public modMC13SVQAStop_stDTType As String
    Public modMC14SVQAStop_stDTType As String
    Public modMC15SVQAStop_stDTType As String
    Public modMC16SVQAStop_stDTType As String
    Public modMC17SVQAStop_stDTType As String
    Public modMC18SVQAStop_stDTType As String
    Public modMC19SVQAStop_stDTType As String

    Public modMC1SVQAStop_stStartTime As String
    Public modMC2SVQAStop_stStartTime As String
    Public modMC3SVQAStop_stStartTime As String
    Public modMC4SVQAStop_stStartTime As String
    Public modMC5SVQAStop_stStartTime As String
    Public modMC6SVQAStop_stStartTime As String
    Public modMC7SVQAStop_stStartTime As String
    Public modMC8SVQAStop_stStartTime As String
    Public modMC9SVQAStop_stStartTime As String
    Public modMC10SVQAStop_stStartTime As String
    Public modMC11SVQAStop_stStartTime As String
    Public modMC12SVQAStop_stStartTime As String
    Public modMC13SVQAStop_stStartTime As String
    Public modMC14SVQAStop_stStartTime As String
    Public modMC15SVQAStop_stStartTime As String
    Public modMC16SVQAStop_stStartTime As String
    Public modMC17SVQAStop_stStartTime As String
    Public modMC18SVQAStop_stStartTime As String
    Public modMC19SVQAStop_stStartTime As String

    Public modMC1SVQAStop_stDTReason As String
    Public modMC2SVQAStop_stDTReason As String
    Public modMC3SVQAStop_stDTReason As String
    Public modMC4SVQAStop_stDTReason As String
    Public modMC5SVQAStop_stDTReason As String
    Public modMC6SVQAStop_stDTReason As String
    Public modMC7SVQAStop_stDTReason As String
    Public modMC8SVQAStop_stDTReason As String
    Public modMC9SVQAStop_stDTReason As String
    Public modMC10SVQAStop_stDTReason As String
    Public modMC11SVQAStop_stDTReason As String
    Public modMC12SVQAStop_stDTReason As String
    Public modMC13SVQAStop_stDTReason As String
    Public modMC14SVQAStop_stDTReason As String
    Public modMC15SVQAStop_stDTReason As String
    Public modMC16SVQAStop_stDTReason As String
    Public modMC17SVQAStop_stDTReason As String
    Public modMC18SVQAStop_stDTReason As String
    Public modMC19SVQAStop_stDTReason As String

    Public modMC1SVQAStop_stDTCMeasure As String
    Public modMC2SVQAStop_stDTCMeasure As String
    Public modMC3SVQAStop_stDTCMeasure As String
    Public modMC4SVQAStop_stDTCMeasure As String
    Public modMC5SVQAStop_stDTCMeasure As String
    Public modMC6SVQAStop_stDTCMeasure As String
    Public modMC7SVQAStop_stDTCMeasure As String
    Public modMC8SVQAStop_stDTCMeasure As String
    Public modMC9SVQAStop_stDTCMeasure As String
    Public modMC10SVQAStop_stDTCMeasure As String
    Public modMC11SVQAStop_stDTCMeasure As String
    Public modMC12SVQAStop_stDTCMeasure As String
    Public modMC13SVQAStop_stDTCMeasure As String
    Public modMC14SVQAStop_stDTCMeasure As String
    Public modMC15SVQAStop_stDTCMeasure As String
    Public modMC16SVQAStop_stDTCMeasure As String
    Public modMC17SVQAStop_stDTCMeasure As String
    Public modMC18SVQAStop_stDTCMeasure As String
    Public modMC19SVQAStop_stDTCMeasure As String

    Public modMC1SVQAStop_stACKDate As String
    Public modMC2SVQAStop_stACKDate As String
    Public modMC3SVQAStop_stACKDate As String
    Public modMC4SVQAStop_stACKDate As String
    Public modMC5SVQAStop_stACKDate As String
    Public modMC6SVQAStop_stACKDate As String
    Public modMC7SVQAStop_stACKDate As String
    Public modMC8SVQAStop_stACKDate As String
    Public modMC9SVQAStop_stACKDate As String
    Public modMC10SVQAStop_stACKDate As String
    Public modMC11SVQAStop_stACKDate As String
    Public modMC12SVQAStop_stACKDate As String
    Public modMC13SVQAStop_stACKDate As String
    Public modMC14SVQAStop_stACKDate As String
    Public modMC15SVQAStop_stACKDate As String
    Public modMC16SVQAStop_stACKDate As String
    Public modMC17SVQAStop_stACKDate As String
    Public modMC18SVQAStop_stACKDate As String
    Public modMC19SVQAStop_stACKDate As String

    Public modMC1SVQAStop_stEndTime As String
    Public modMC2SVQAStop_stEndTime As String
    Public modMC3SVQAStop_stEndTime As String
    Public modMC4SVQAStop_stEndTime As String
    Public modMC5SVQAStop_stEndTime As String
    Public modMC6SVQAStop_stEndTime As String
    Public modMC7SVQAStop_stEndTime As String
    Public modMC8SVQAStop_stEndTime As String
    Public modMC9SVQAStop_stEndTime As String
    Public modMC10SVQAStop_stEndTime As String
    Public modMC11SVQAStop_stEndTime As String
    Public modMC12SVQAStop_stEndTime As String
    Public modMC13SVQAStop_stEndTime As String
    Public modMC14SVQAStop_stEndTime As String
    Public modMC15SVQAStop_stEndTime As String
    Public modMC16SVQAStop_stEndTime As String
    Public modMC17SVQAStop_stEndTime As String
    Public modMC18SVQAStop_stEndTime As String
    Public modMC19SVQAStop_stEndTime As String

    Public modMC1SVQAStop_stRunTime As String
    Public modMC2SVQAStop_stRunTime As String
    Public modMC3SVQAStop_stRunTime As String
    Public modMC4SVQAStop_stRunTime As String
    Public modMC5SVQAStop_stRunTime As String
    Public modMC6SVQAStop_stRunTime As String
    Public modMC7SVQAStop_stRunTime As String
    Public modMC8SVQAStop_stRunTime As String
    Public modMC9SVQAStop_stRunTime As String
    Public modMC10SVQAStop_stRunTime As String
    Public modMC11SVQAStop_stRunTime As String
    Public modMC12SVQAStop_stRunTime As String
    Public modMC13SVQAStop_stRunTime As String
    Public modMC14SVQAStop_stRunTime As String
    Public modMC15SVQAStop_stRunTime As String
    Public modMC16SVQAStop_stRunTime As String
    Public modMC17SVQAStop_stRunTime As String
    Public modMC18SVQAStop_stRunTime As String
    Public modMC19SVQAStop_stRunTime As String

    Public modMC1SVQAStop_iTtlDTMins As Integer
    Public modMC2SVQAStop_iTtlDTMins As Integer
    Public modMC3SVQAStop_iTtlDTMins As Integer
    Public modMC4SVQAStop_iTtlDTMins As Integer
    Public modMC5SVQAStop_iTtlDTMins As Integer
    Public modMC6SVQAStop_iTtlDTMins As Integer
    Public modMC7SVQAStop_iTtlDTMins As Integer
    Public modMC8SVQAStop_iTtlDTMins As Integer
    Public modMC9SVQAStop_iTtlDTMins As Integer
    Public modMC10SVQAStop_iTtlDTMins As Integer
    Public modMC11SVQAStop_iTtlDTMins As Integer
    Public modMC12SVQAStop_iTtlDTMins As Integer
    Public modMC13SVQAStop_iTtlDTMins As Integer
    Public modMC14SVQAStop_iTtlDTMins As Integer
    Public modMC15SVQAStop_iTtlDTMins As Integer
    Public modMC16SVQAStop_iTtlDTMins As Integer
    Public modMC17SVQAStop_iTtlDTMins As Integer
    Public modMC18SVQAStop_iTtlDTMins As Integer
    Public modMC19SVQAStop_iTtlDTMins As Integer

    Public modMC1SVQAStop_iTtlRepTimeMins As Integer
    Public modMC2SVQAStop_iTtlRepTimeMins As Integer
    Public modMC3SVQAStop_iTtlRepTimeMins As Integer
    Public modMC4SVQAStop_iTtlRepTimeMins As Integer
    Public modMC5SVQAStop_iTtlRepTimeMins As Integer
    Public modMC6SVQAStop_iTtlRepTimeMins As Integer
    Public modMC7SVQAStop_iTtlRepTimeMins As Integer
    Public modMC8SVQAStop_iTtlRepTimeMins As Integer
    Public modMC9SVQAStop_iTtlRepTimeMins As Integer
    Public modMC10SVQAStop_iTtlRepTimeMins As Integer
    Public modMC11SVQAStop_iTtlRepTimeMins As Integer
    Public modMC12SVQAStop_iTtlRepTimeMins As Integer
    Public modMC13SVQAStop_iTtlRepTimeMins As Integer
    Public modMC14SVQAStop_iTtlRepTimeMins As Integer
    Public modMC15SVQAStop_iTtlRepTimeMins As Integer
    Public modMC16SVQAStop_iTtlRepTimeMins As Integer
    Public modMC17SVQAStop_iTtlRepTimeMins As Integer
    Public modMC18SVQAStop_iTtlRepTimeMins As Integer
    Public modMC19SVQAStop_iTtlRepTimeMins As Integer

    Public modMC1SVQAStop_stForQAVeri As String
    Public modMC2SVQAStop_stForQAVeri As String
    Public modMC3SVQAStop_stForQAVeri As String
    Public modMC4SVQAStop_stForQAVeri As String
    Public modMC5SVQAStop_stForQAVeri As String
    Public modMC6SVQAStop_stForQAVeri As String
    Public modMC7SVQAStop_stForQAVeri As String
    Public modMC8SVQAStop_stForQAVeri As String
    Public modMC9SVQAStop_stForQAVeri As String
    Public modMC10SVQAStop_stForQAVeri As String
    Public modMC11SVQAStop_stForQAVeri As String
    Public modMC12SVQAStop_stForQAVeri As String
    Public modMC13SVQAStop_stForQAVeri As String
    Public modMC14SVQAStop_stForQAVeri As String
    Public modMC15SVQAStop_stForQAVeri As String
    Public modMC16SVQAStop_stForQAVeri As String
    Public modMC17SVQAStop_stForQAVeri As String
    Public modMC18SVQAStop_stForQAVeri As String
    Public modMC19SVQAStop_stForQAVeri As String

    Public modMC1SVQAStop_iTtlQAVerMins As Integer
    Public modMC2SVQAStop_iTtlQAVerMins As Integer
    Public modMC3SVQAStop_iTtlQAVerMins As Integer
    Public modMC4SVQAStop_iTtlQAVerMins As Integer
    Public modMC5SVQAStop_iTtlQAVerMins As Integer
    Public modMC6SVQAStop_iTtlQAVerMins As Integer
    Public modMC7SVQAStop_iTtlQAVerMins As Integer
    Public modMC8SVQAStop_iTtlQAVerMins As Integer
    Public modMC9SVQAStop_iTtlQAVerMins As Integer
    Public modMC10SVQAStop_iTtlQAVerMins As Integer
    Public modMC11SVQAStop_iTtlQAVerMins As Integer
    Public modMC12SVQAStop_iTtlQAVerMins As Integer
    Public modMC13SVQAStop_iTtlQAVerMins As Integer
    Public modMC14SVQAStop_iTtlQAVerMins As Integer
    Public modMC15SVQAStop_iTtlQAVerMins As Integer
    Public modMC16SVQAStop_iTtlQAVerMins As Integer
    Public modMC17SVQAStop_iTtlQAVerMins As Integer
    Public modMC18SVQAStop_iTtlQAVerMins As Integer
    Public modMC19SVQAStop_iTtlQAVerMins As Integer

    Public modMC1SVQAStop_iTtlFailFeq As Integer
    Public modMC2SVQAStop_iTtlFailFeq As Integer
    Public modMC3SVQAStop_iTtlFailFeq As Integer
    Public modMC4SVQAStop_iTtlFailFeq As Integer
    Public modMC5SVQAStop_iTtlFailFeq As Integer
    Public modMC6SVQAStop_iTtlFailFeq As Integer
    Public modMC7SVQAStop_iTtlFailFeq As Integer
    Public modMC8SVQAStop_iTtlFailFeq As Integer
    Public modMC9SVQAStop_iTtlFailFeq As Integer
    Public modMC10SVQAStop_iTtlFailFeq As Integer
    Public modMC11SVQAStop_iTtlFailFeq As Integer
    Public modMC12SVQAStop_iTtlFailFeq As Integer
    Public modMC13SVQAStop_iTtlFailFeq As Integer
    Public modMC14SVQAStop_iTtlFailFeq As Integer
    Public modMC15SVQAStop_iTtlFailFeq As Integer
    Public modMC16SVQAStop_iTtlFailFeq As Integer
    Public modMC17SVQAStop_iTtlFailFeq As Integer
    Public modMC18SVQAStop_iTtlFailFeq As Integer
    Public modMC19SVQAStop_iTtlFailFeq As Integer

    Public modMC1SVQAStop_stDTStatus As String
    Public modMC2SVQAStop_stDTStatus As String
    Public modMC3SVQAStop_stDTStatus As String
    Public modMC4SVQAStop_stDTStatus As String
    Public modMC5SVQAStop_stDTStatus As String
    Public modMC6SVQAStop_stDTStatus As String
    Public modMC7SVQAStop_stDTStatus As String
    Public modMC8SVQAStop_stDTStatus As String
    Public modMC9SVQAStop_stDTStatus As String
    Public modMC10SVQAStop_stDTStatus As String
    Public modMC11SVQAStop_stDTStatus As String
    Public modMC12SVQAStop_stDTStatus As String
    Public modMC13SVQAStop_stDTStatus As String
    Public modMC14SVQAStop_stDTStatus As String
    Public modMC15SVQAStop_stDTStatus As String
    Public modMC16SVQAStop_stDTStatus As String
    Public modMC17SVQAStop_stDTStatus As String
    Public modMC18SVQAStop_stDTStatus As String
    Public modMC19SVQAStop_stDTStatus As String

    Public modMC1SVQAStop_stJOCode As String
    Public modMC2SVQAStop_stJOCode As String
    Public modMC3SVQAStop_stJOCode As String
    Public modMC4SVQAStop_stJOCode As String
    Public modMC5SVQAStop_stJOCode As String
    Public modMC6SVQAStop_stJOCode As String
    Public modMC7SVQAStop_stJOCode As String
    Public modMC8SVQAStop_stJOCode As String
    Public modMC9SVQAStop_stJOCode As String
    Public modMC10SVQAStop_stJOCode As String
    Public modMC11SVQAStop_stJOCode As String
    Public modMC12SVQAStop_stJOCode As String
    Public modMC13SVQAStop_stJOCode As String
    Public modMC14SVQAStop_stJOCode As String
    Public modMC15SVQAStop_stJOCode As String
    Public modMC16SVQAStop_stJOCode As String
    Public modMC17SVQAStop_stJOCode As String
    Public modMC18SVQAStop_stJOCode As String
    Public modMC19SVQAStop_stJOCode As String

    Public modMC1SVQAStop_stMCId As String
    Public modMC2SVQAStop_stMCId As String
    Public modMC3SVQAStop_stMCId As String
    Public modMC4SVQAStop_stMCId As String
    Public modMC5SVQAStop_stMCId As String
    Public modMC6SVQAStop_stMCId As String
    Public modMC7SVQAStop_stMCId As String
    Public modMC8SVQAStop_stMCId As String
    Public modMC9SVQAStop_stMCId As String
    Public modMC10SVQAStop_stMCId As String
    Public modMC11SVQAStop_stMCId As String
    Public modMC12SVQAStop_stMCId As String
    Public modMC13SVQAStop_stMCId As String
    Public modMC14SVQAStop_stMCId As String
    Public modMC15SVQAStop_stMCId As String
    Public modMC16SVQAStop_stMCId As String
    Public modMC17SVQAStop_stMCId As String
    Public modMC18SVQAStop_stMCId As String
    Public modMC19SVQAStop_stMCId As String

    Public modMC1SVQAStop_stVeriByQA As String
    Public modMC2SVQAStop_stVeriByQA As String
    Public modMC3SVQAStop_stVeriByQA As String
    Public modMC4SVQAStop_stVeriByQA As String
    Public modMC5SVQAStop_stVeriByQA As String
    Public modMC6SVQAStop_stVeriByQA As String
    Public modMC7SVQAStop_stVeriByQA As String
    Public modMC8SVQAStop_stVeriByQA As String
    Public modMC9SVQAStop_stVeriByQA As String
    Public modMC10SVQAStop_stVeriByQA As String
    Public modMC11SVQAStop_stVeriByQA As String
    Public modMC12SVQAStop_stVeriByQA As String
    Public modMC13SVQAStop_stVeriByQA As String
    Public modMC14SVQAStop_stVeriByQA As String
    Public modMC15SVQAStop_stVeriByQA As String
    Public modMC16SVQAStop_stVeriByQA As String
    Public modMC17SVQAStop_stVeriByQA As String
    Public modMC18SVQAStop_stVeriByQA As String
    Public modMC19SVQAStop_stVeriByQA As String

    Public modMC1SVQAStop_stCreatedBy As String
    Public modMC2SVQAStop_stCreatedBy As String
    Public modMC3SVQAStop_stCreatedBy As String
    Public modMC4SVQAStop_stCreatedBy As String
    Public modMC5SVQAStop_stCreatedBy As String
    Public modMC6SVQAStop_stCreatedBy As String
    Public modMC7SVQAStop_stCreatedBy As String
    Public modMC8SVQAStop_stCreatedBy As String
    Public modMC9SVQAStop_stCreatedBy As String
    Public modMC10SVQAStop_stCreatedBy As String
    Public modMC11SVQAStop_stCreatedBy As String
    Public modMC12SVQAStop_stCreatedBy As String
    Public modMC13SVQAStop_stCreatedBy As String
    Public modMC14SVQAStop_stCreatedBy As String
    Public modMC15SVQAStop_stCreatedBy As String
    Public modMC16SVQAStop_stCreatedBy As String
    Public modMC17SVQAStop_stCreatedBy As String
    Public modMC18SVQAStop_stCreatedBy As String
    Public modMC19SVQAStop_stCreatedBy As String
End Module
