Public Class rgbColors
    Public Shared rgb_White As Color = Color.FromArgb(255, 255, 255)
    Public Shared rgb_Silver As Color = Color.FromArgb(192, 192, 192)
    Public Shared rgb_Gray As Color = Color.FromArgb(128, 128, 128)
    Public Shared rgb_Black1 As Color = Color.FromArgb(0, 0, 0)
    Public Shared rgb_Red As Color = Color.FromArgb(255, 0, 0)
    Public Shared rgb_Maroon As Color = Color.FromArgb(128, 0, 0)
    Public Shared rgb_Yellow As Color = Color.FromArgb(255, 255, 0)
    Public Shared rgb_Olive As Color = Color.FromArgb(128, 128, 0)
    Public Shared rgb_Lime As Color = Color.FromArgb(0, 255, 0)
    Public Shared rgb_Green As Color = Color.FromArgb(0, 128, 0)
    Public Shared rgb_Aqua As Color = Color.FromArgb(0, 255, 255)
    Public Shared rgb_Teal As Color = Color.FromArgb(0, 128, 128)
    Public Shared rgb_Blue As Color = Color.FromArgb(0, 0, 255)
    Public Shared rgb_Crimson As Color = Color.FromArgb(220, 20, 60)
    Public Shared rgb_Black2 As Color = Color.FromArgb(41, 39, 40)
    Public Shared rgb_Fuchsia As Color = Color.FromArgb(255, 0, 255)
    Public Shared rgb_RoyalBlue As Color = Color.FromArgb(65, 105, 225)
    Public Shared rgb_NavyBlue As Color = Color.FromArgb(0, 0, 128)
    Public Shared rgb_MistyBlue As Color = Color.FromArgb(160, 175, 183)
    Public Shared rgb_MidnightBlue As Color = Color.FromArgb(12, 97, 112)
    Public Shared rgb_BlueGreen As Color = Color.FromArgb(55, 190, 176)
    Public Shared rgb_TiffanyBlue As Color = Color.FromArgb(164, 229, 224)
    Public Shared rgb_BabyBlue As Color = Color.FromArgb(219, 245, 240)
    Public Shared rgb_Control As Color = Color.FromArgb(240, 240, 240)
    Public Shared rgb_MCpicBaseColor As Color = Color.FromArgb(37, 55, 77)
    Public Shared rgb_OrangeProguard As Color = Color.FromArgb(254, 79, 0)
End Class
