Module WorkOrderLoading
    Public stJOOrderCode As String
    Public stJOPartNo1 As String
    Public stJOPartNo2 As String
    Public stJOMoldCavPart1 As String
    Public stJOMoldCavPart2 As String
    Public stJOQuantity As String
    Public stJOCycleTime As String
    Public stJOStartTime As String
    Public stJOMoldID As String
    Public stMachineID As String

    'UNLOADING
    Public stJOMachineID_Unloading As String
    Public bolUpdateAndUnload As Boolean
    Public preUnloadDetails_MCId As String
    Public preUnloadDetails_SftCode As String
    Public preUnloadDetails_JOCode As String
    Public preUnloadDetails_MoldId As String
    Public preUnloadDetails_PN1 As String
    Public preUnloadDetails_PN2 As String
    Public preUnloadDetails_CavP1 As Integer
    Public preUnloadDetails_CavP2 As Integer
    Public preUnloadDetails_JoQty As Integer
    Public preUnloadDetails_CycleTime As Integer
    Public preUnloadDetails_StartTime As String
    Public preUnloadDetails_EndTime As String
    Public preUnloadDetails_LoadStat As String
    Public preUnloadDetails_ProdnStat As String
    Public preUnloadDetails_LoadedBy As String
    Public preUnloadDetails_UnloadedBy As String
    Public preUnloadDetails_Confirmed As Boolean

    Public stJOMC1 As String
    Public stJOMC2 As String
    Public stJOMC3 As String
    Public stJOMC4 As String
    Public stJOMC5 As String
    Public stJOMC6 As String
    Public stJOMC7 As String
    Public stJOMC8 As String
    Public stJOMC9 As String
    Public stJOMC10 As String
    Public stJOMC11 As String
    Public stJOMC12 As String
    Public stJOMC13 As String
    Public stJOMC14 As String
    Public stJOMC15 As String
    Public stJOMC16 As String
    Public stJOMC17 As String
    Public stJOMC18 As String
    Public stJOMC19 As String

    Public stJOPartNo1MC1 As String
    Public stJOPartNo1MC2 As String
    Public stJOPartNo1MC3 As String
    Public stJOPartNo1MC4 As String
    Public stJOPartNo1MC5 As String
    Public stJOPartNo1MC6 As String
    Public stJOPartNo1MC7 As String
    Public stJOPartNo1MC8 As String
    Public stJOPartNo1MC9 As String
    Public stJOPartNo1MC10 As String
    Public stJOPartNo1MC11 As String
    Public stJOPartNo1MC12 As String
    Public stJOPartNo1MC13 As String
    Public stJOPartNo1MC14 As String
    Public stJOPartNo1MC15 As String
    Public stJOPartNo1MC16 As String
    Public stJOPartNo1MC17 As String
    Public stJOPartNo1MC18 As String
    Public stJOPartNo1MC19 As String

    Public stJOPartNo2MC1 As String
    Public stJOPartNo2MC2 As String
    Public stJOPartNo2MC3 As String
    Public stJOPartNo2MC4 As String
    Public stJOPartNo2MC5 As String
    Public stJOPartNo2MC6 As String
    Public stJOPartNo2MC7 As String
    Public stJOPartNo2MC8 As String
    Public stJOPartNo2MC9 As String
    Public stJOPartNo2MC10 As String
    Public stJOPartNo2MC11 As String
    Public stJOPartNo2MC12 As String
    Public stJOPartNo2MC13 As String
    Public stJOPartNo2MC14 As String
    Public stJOPartNo2MC15 As String
    Public stJOPartNo2MC16 As String
    Public stJOPartNo2MC17 As String
    Public stJOPartNo2MC18 As String
    Public stJOPartNo2MC19 As String

    Public stJOPartNo3MC1 As String
    Public stJOPartNo3MC2 As String
    Public stJOPartNo3MC3 As String
    Public stJOPartNo3MC4 As String
    Public stJOPartNo3MC5 As String
    Public stJOPartNo3MC6 As String
    Public stJOPartNo3MC7 As String
    Public stJOPartNo3MC8 As String
    Public stJOPartNo3MC9 As String
    Public stJOPartNo3MC10 As String
    Public stJOPartNo3MC11 As String
    Public stJOPartNo3MC12 As String
    Public stJOPartNo3MC13 As String
    Public stJOPartNo3MC14 As String
    Public stJOPartNo3MC15 As String
    Public stJOPartNo3MC16 As String
    Public stJOPartNo3MC17 As String
    Public stJOPartNo3MC18 As String
    Public stJOPartNo3MC19 As String

    Public stJOPartNo4MC1 As String
    Public stJOPartNo4MC2 As String
    Public stJOPartNo4MC3 As String
    Public stJOPartNo4MC4 As String
    Public stJOPartNo4MC5 As String
    Public stJOPartNo4MC6 As String
    Public stJOPartNo4MC7 As String
    Public stJOPartNo4MC8 As String
    Public stJOPartNo4MC9 As String
    Public stJOPartNo4MC10 As String
    Public stJOPartNo4MC11 As String
    Public stJOPartNo4MC12 As String
    Public stJOPartNo4MC13 As String
    Public stJOPartNo4MC14 As String
    Public stJOPartNo4MC15 As String
    Public stJOPartNo4MC16 As String
    Public stJOPartNo4MC17 As String
    Public stJOPartNo4MC18 As String
    Public stJOPartNo4MC19 As String

    Public stJOMoldCavP1MC1 As String
    Public stJOMoldCavP1MC2 As String
    Public stJOMoldCavP1MC3 As String
    Public stJOMoldCavP1MC4 As String
    Public stJOMoldCavP1MC5 As String
    Public stJOMoldCavP1MC6 As String
    Public stJOMoldCavP1MC7 As String
    Public stJOMoldCavP1MC8 As String
    Public stJOMoldCavP1MC9 As String
    Public stJOMoldCavP1MC10 As String
    Public stJOMoldCavP1MC11 As String
    Public stJOMoldCavP1MC12 As String
    Public stJOMoldCavP1MC13 As String
    Public stJOMoldCavP1MC14 As String
    Public stJOMoldCavP1MC15 As String
    Public stJOMoldCavP1MC16 As String
    Public stJOMoldCavP1MC17 As String
    Public stJOMoldCavP1MC18 As String
    Public stJOMoldCavP1MC19 As String

    Public stJOMoldCavP2MC1 As String
    Public stJOMoldCavP2MC2 As String
    Public stJOMoldCavP2MC3 As String
    Public stJOMoldCavP2MC4 As String
    Public stJOMoldCavP2MC5 As String
    Public stJOMoldCavP2MC6 As String
    Public stJOMoldCavP2MC7 As String
    Public stJOMoldCavP2MC8 As String
    Public stJOMoldCavP2MC9 As String
    Public stJOMoldCavP2MC10 As String
    Public stJOMoldCavP2MC11 As String
    Public stJOMoldCavP2MC12 As String
    Public stJOMoldCavP2MC13 As String
    Public stJOMoldCavP2MC14 As String
    Public stJOMoldCavP2MC15 As String
    Public stJOMoldCavP2MC16 As String
    Public stJOMoldCavP2MC17 As String
    Public stJOMoldCavP2MC18 As String
    Public stJOMoldCavP2MC19 As String

    Public stJOMoldCavP3MC1 As String
    Public stJOMoldCavP3MC2 As String
    Public stJOMoldCavP3MC3 As String
    Public stJOMoldCavP3MC4 As String
    Public stJOMoldCavP3MC5 As String
    Public stJOMoldCavP3MC6 As String
    Public stJOMoldCavP3MC7 As String
    Public stJOMoldCavP3MC8 As String
    Public stJOMoldCavP3MC9 As String
    Public stJOMoldCavP3MC10 As String
    Public stJOMoldCavP3MC11 As String
    Public stJOMoldCavP3MC12 As String
    Public stJOMoldCavP3MC13 As String
    Public stJOMoldCavP3MC14 As String
    Public stJOMoldCavP3MC15 As String
    Public stJOMoldCavP3MC16 As String
    Public stJOMoldCavP3MC17 As String
    Public stJOMoldCavP3MC18 As String
    Public stJOMoldCavP3MC19 As String

    Public stJOMoldCavP4MC1 As String
    Public stJOMoldCavP4MC2 As String
    Public stJOMoldCavP4MC3 As String
    Public stJOMoldCavP4MC4 As String
    Public stJOMoldCavP4MC5 As String
    Public stJOMoldCavP4MC6 As String
    Public stJOMoldCavP4MC7 As String
    Public stJOMoldCavP4MC8 As String
    Public stJOMoldCavP4MC9 As String
    Public stJOMoldCavP4MC10 As String
    Public stJOMoldCavP4MC11 As String
    Public stJOMoldCavP4MC12 As String
    Public stJOMoldCavP4MC13 As String
    Public stJOMoldCavP4MC14 As String
    Public stJOMoldCavP4MC15 As String
    Public stJOMoldCavP4MC16 As String
    Public stJOMoldCavP4MC17 As String
    Public stJOMoldCavP4MC18 As String
    Public stJOMoldCavP4MC19 As String

    Public stJOQuantityMC1 As String
    Public stJOQuantityMC2 As String
    Public stJOQuantityMC3 As String
    Public stJOQuantityMC4 As String
    Public stJOQuantityMC5 As String
    Public stJOQuantityMC6 As String
    Public stJOQuantityMC7 As String
    Public stJOQuantityMC8 As String
    Public stJOQuantityMC9 As String
    Public stJOQuantityMC10 As String
    Public stJOQuantityMC11 As String
    Public stJOQuantityMC12 As String
    Public stJOQuantityMC13 As String
    Public stJOQuantityMC14 As String
    Public stJOQuantityMC15 As String
    Public stJOQuantityMC16 As String
    Public stJOQuantityMC17 As String
    Public stJOQuantityMC18 As String
    Public stJOQuantityMC19 As String

    Public stJOCycleTimeMC1 As String
    Public stJOCycleTimeMC2 As String
    Public stJOCycleTimeMC3 As String
    Public stJOCycleTimeMC4 As String
    Public stJOCycleTimeMC5 As String
    Public stJOCycleTimeMC6 As String
    Public stJOCycleTimeMC7 As String
    Public stJOCycleTimeMC8 As String
    Public stJOCycleTimeMC9 As String
    Public stJOCycleTimeMC10 As String
    Public stJOCycleTimeMC11 As String
    Public stJOCycleTimeMC12 As String
    Public stJOCycleTimeMC13 As String
    Public stJOCycleTimeMC14 As String
    Public stJOCycleTimeMC15 As String
    Public stJOCycleTimeMC16 As String
    Public stJOCycleTimeMC17 As String
    Public stJOCycleTimeMC18 As String
    Public stJOCycleTimeMC19 As String

    Public stJOMoldIDMC1 As String
    Public stJOMoldIDMC2 As String
    Public stJOMoldIDMC3 As String
    Public stJOMoldIDMC4 As String
    Public stJOMoldIDMC5 As String
    Public stJOMoldIDMC6 As String
    Public stJOMoldIDMC7 As String
    Public stJOMoldIDMC8 As String
    Public stJOMoldIDMC9 As String
    Public stJOMoldIDMC10 As String
    Public stJOMoldIDMC11 As String
    Public stJOMoldIDMC12 As String
    Public stJOMoldIDMC13 As String
    Public stJOMoldIDMC14 As String
    Public stJOMoldIDMC15 As String
    Public stJOMoldIDMC16 As String
    Public stJOMoldIDMC17 As String
    Public stJOMoldIDMC18 As String
    Public stJOMoldIDMC19 As String

    Public stJOMachineIDMC1 As String
    Public stJOMachineIDMC2 As String
    Public stJOMachineIDMC3 As String
    Public stJOMachineIDMC4 As String
    Public stJOMachineIDMC5 As String
    Public stJOMachineIDMC6 As String
    Public stJOMachineIDMC7 As String
    Public stJOMachineIDMC8 As String
    Public stJOMachineIDMC9 As String
    Public stJOMachineIDMC10 As String
    Public stJOMachineIDMC11 As String
    Public stJOMachineIDMC12 As String
    Public stJOMachineIDMC13 As String
    Public stJOMachineIDMC14 As String
    Public stJOMachineIDMC15 As String
    Public stJOMachineIDMC16 As String
    Public stJOMachineIDMC17 As String
    Public stJOMachineIDMC18 As String
    Public stJOMachineIDMC19 As String

    Public stJOStartTimeMC1 As String
    Public stJOStartTimeMC2 As String
    Public stJOStartTimeMC3 As String
    Public stJOStartTimeMC4 As String
    Public stJOStartTimeMC5 As String
    Public stJOStartTimeMC6 As String
    Public stJOStartTimeMC7 As String
    Public stJOStartTimeMC8 As String
    Public stJOStartTimeMC9 As String
    Public stJOStartTimeMC10 As String
    Public stJOStartTimeMC11 As String
    Public stJOStartTimeMC12 As String
    Public stJOStartTimeMC13 As String
    Public stJOStartTimeMC14 As String
    Public stJOStartTimeMC15 As String
    Public stJOStartTimeMC16 As String
    Public stJOStartTimeMC17 As String
    Public stJOStartTimeMC18 As String
    Public stJOStartTimeMC19 As String

    Public stJOEndTimeMC1 As String
    Public stJOEndTimeMC2 As String
    Public stJOEndTimeMC3 As String
    Public stJOEndTimeMC4 As String
    Public stJOEndTimeMC5 As String
    Public stJOEndTimeMC6 As String
    Public stJOEndTimeMC7 As String
    Public stJOEndTimeMC8 As String
    Public stJOEndTimeMC9 As String
    Public stJOEndTimeMC10 As String
    Public stJOEndTimeMC11 As String
    Public stJOEndTimeMC12 As String
    Public stJOEndTimeMC13 As String
    Public stJOEndTimeMC14 As String
    Public stJOEndTimeMC15 As String
    Public stJOEndTimeMC16 As String
    Public stJOEndTimeMC17 As String
    Public stJOEndTimeMC18 As String
    Public stJOEndTimeMC19 As String

    Public bolJOLoadConfirm As Boolean
    Public bolJOLoadedatHome As Boolean
    Public stJOLoadedBy As String

    Public JOloadBtnClick As Boolean
    Public JOUnloadBtnClick As Boolean
    Public JOUnloadBtn2Click As Boolean
    Public JOLoadBtn2Click As Boolean
    Public bolJOUnloadConfirm As Boolean
    Public bolJOUnloadedatHome As Boolean
    Public stJOUnloadedBy As String

    Public ckbMachine1 As Boolean
    Public ckbMachine2 As Boolean
    Public ckbMachine3 As Boolean
    Public ckbMachine4 As Boolean
    Public ckbMachine5 As Boolean
    Public ckbMachine6 As Boolean
    Public ckbMachine7 As Boolean
    Public ckbMachine8 As Boolean
    Public ckbMachine9 As Boolean
    Public ckbMachine10 As Boolean
    Public ckbMachine11 As Boolean
    Public ckbMachine12 As Boolean
    Public ckbMachine13 As Boolean
    Public ckbMachine14 As Boolean
    Public ckbMachine15 As Boolean
    Public ckbMachine16 As Boolean
    Public ckbMachine17 As Boolean
    Public ckbMachine18 As Boolean
    Public ckbMachine19 As Boolean

    Public iPlanProdTimeMC1 As Decimal
    Public iPlanProdTimeMC2 As Decimal
    Public iPlanProdTimeMC3 As Decimal
    Public iPlanProdTimeMC4 As Decimal
    Public iPlanProdTimeMC5 As Decimal
    Public iPlanProdTimeMC6 As Decimal
    Public iPlanProdTimeMC7 As Decimal
    Public iPlanProdTimeMC8 As Decimal
    Public iPlanProdTimeMC9 As Decimal
    Public iPlanProdTimeMC10 As Decimal
    Public iPlanProdTimeMC11 As Decimal
    Public iPlanProdTimeMC12 As Decimal
    Public iPlanProdTimeMC13 As Decimal
    Public iPlanProdTimeMC14 As Decimal
    Public iPlanProdTimeMC15 As Decimal
    Public iPlanProdTimeMC16 As Decimal
    Public iPlanProdTimeMC17 As Decimal
    Public iPlanProdTimeMC18 As Decimal
    Public iPlanProdTimeMC19 As Decimal

    'JO PROGRESS STATS
    Public PlanCompleteMC1 As Boolean
    Public PlanCompleteMC2 As Boolean
    Public PlanCompleteMC3 As Boolean
    Public PlanCompleteMC4 As Boolean
    Public PlanCompleteMC5 As Boolean
    Public PlanCompleteMC6 As Boolean
    Public PlanCompleteMC7 As Boolean
    Public PlanCompleteMC8 As Boolean
    Public PlanCompleteMC9 As Boolean
    Public PlanCompleteMC10 As Boolean
    Public PlanCompleteMC11 As Boolean
    Public PlanCompleteMC12 As Boolean
    Public PlanCompleteMC13 As Boolean
    Public PlanCompleteMC14 As Boolean
    Public PlanCompleteMC15 As Boolean
    Public PlanCompleteMC16 As Boolean
    Public PlanCompleteMC17 As Boolean
    Public PlanCompleteMC18 As Boolean
    Public PlanCompleteMC19 As Boolean

    'JOB ORDER LOADED FLAG 
    Public modJOLoadedFlagMC1 As Boolean
    Public modJOLoadedFlagMC2 As Boolean
    Public modJOLoadedFlagMC3 As Boolean
    Public modJOLoadedFlagMC4 As Boolean
    Public modJOLoadedFlagMC5 As Boolean
    Public modJOLoadedFlagMC6 As Boolean
    Public modJOLoadedFlagMC7 As Boolean
    Public modJOLoadedFlagMC8 As Boolean
    Public modJOLoadedFlagMC9 As Boolean
    Public modJOLoadedFlagMC10 As Boolean
    Public modJOLoadedFlagMC11 As Boolean
    Public modJOLoadedFlagMC12 As Boolean
    Public modJOLoadedFlagMC13 As Boolean
    Public modJOLoadedFlagMC14 As Boolean
    Public modJOLoadedFlagMC15 As Boolean
    Public modJOLoadedFlagMC16 As Boolean
    Public modJOLoadedFlagMC17 As Boolean
    Public modJOLoadedFlagMC18 As Boolean
    Public modJOLoadedFlagMC19 As Boolean

    Public stJORejectQTyP1MC1 As Integer
    Public stJORejectQTyP1MC2 As Integer
    Public stJORejectQTyP1MC3 As Integer
    Public stJORejectQTyP1MC4 As Integer
    Public stJORejectQTyP1MC5 As Integer
    Public stJORejectQTyP1MC6 As Integer
    Public stJORejectQTyP1MC7 As Integer
    Public stJORejectQTyP1MC8 As Integer
    Public stJORejectQTyP1MC9 As Integer
    Public stJORejectQTyP1MC10 As Integer
    Public stJORejectQTyP1MC11 As Integer
    Public stJORejectQTyP1MC12 As Integer
    Public stJORejectQTyP1MC13 As Integer
    Public stJORejectQTyP1MC14 As Integer
    Public stJORejectQTyP1MC15 As Integer
    Public stJORejectQTyP1MC16 As Integer
    Public stJORejectQTyP1MC17 As Integer
    Public stJORejectQTyP1MC18 As Integer
    Public stJORejectQTyP1MC19 As Integer

    Public stJORejectQTyP2MC1 As Integer
    Public stJORejectQTyP2MC2 As Integer
    Public stJORejectQTyP2MC3 As Integer
    Public stJORejectQTyP2MC4 As Integer
    Public stJORejectQTyP2MC5 As Integer
    Public stJORejectQTyP2MC6 As Integer
    Public stJORejectQTyP2MC7 As Integer
    Public stJORejectQTyP2MC8 As Integer
    Public stJORejectQTyP2MC9 As Integer
    Public stJORejectQTyP2MC10 As Integer
    Public stJORejectQTyP2MC11 As Integer
    Public stJORejectQTyP2MC12 As Integer
    Public stJORejectQTyP2MC13 As Integer
    Public stJORejectQTyP2MC14 As Integer
    Public stJORejectQTyP2MC15 As Integer
    Public stJORejectQTyP2MC16 As Integer
    Public stJORejectQTyP2MC17 As Integer
    Public stJORejectQTyP2MC18 As Integer
    Public stJORejectQTyP2MC19 As Integer

    Public modJOLoadedBy As String
    Public modJOUnloadeBy As String


    'JOB ORDER LOADING NEW PROCESS
    Public modJOLoaded_JOCode As String
    Public modJOLoaded_MoldID As String
    Public modJOLoaded_JOQty As Integer
    Public modJOLoaded_MachineId As String
    Public modJOLoaded_LoadFlag As Boolean

    Public preLDJODetail_ShifCode As String
    Public preLDJODetail_MachineId As String
    Public preLDJODetail_MoldId As String
    Public preLDJODetail_JOCode As String
    Public preLDJODetail_PN1 As String
    Public preLDJODetail_PN2 As String
    Public preLDJODetail_CavPN1 As Integer
    Public preLDJODetail_CavPN2 As Integer
    Public preLDJODetail_PlanQty As Integer
    Public preLDJODetail_CycleTime As Integer
    Public preLDJODetail_StartTime As String
    Public preLDJODetail_LoadedBy As String
    Public preLDJODetail_Confirm As Boolean

End Module
